### PR TITLE
create license key component

### PR DESCRIPTION
**Pull request by sunnyzanchi**
## known issues
- you can tab to the "account license key" text and hit enter to open the popover, but can't tab to the buttons inside it
- clicking the "account license key" text after hovering over it causes the animation to play again. this isn't as important but still looks silly

## screenshots:

Screen Shot 2023-01-27 at 5 47 38 PM
Screen Shot 2023-01-27 at 5 47 45 PM

### CODE REVIEW

**Review by tabathadelane — APPROVED** [review]

**Comment by roadlittledawn** [comment]
should we some doc to package [README](https://github.com/newrelic/gatsby-theme-newrelic/blob/sunny/license-key-component/README.md) for this?

**Comment by sunnyzanchi** [comment]
> should we some doc to package [README](https://github.com/newrelic/gatsby-theme-newrelic/blob/sunny/license-key-component/README.md) for this?

definitely, i'll go ahead and add it

**Review by clarkmcadoo — DISMISSED** [review]

**Comment by roadlittledawn** [comment]
another thing i'm seeing. do we expect two tessen events (`TTHEME_LicenseKey_opened`) to fire, one on opening (on hover) the popup and another when it closes?

https://user-images.githubusercontent.com/2952843/216176733-cf8051c2-adc3-4fd4-9258-760e962daf83.mp4

**Comment by sunnyzanchi** [comment]
> another thing i'm seeing. do we expect two tessen events (`TTHEME_LicenseKey_opened`) to fire, one on opening (on hover) the popup and another when it closes?
> 2023-02-01_14-18-23.mp4

ah good catch. just fixed

**Review by clarkmcadoo — APPROVED** [review]

**Pull request merged**
