### PR TITLE
chore: upgrade gatsby to v3.8

### PR DESCRIPTION
**Pull request by rudouglas**
Along with plugins

### CODE REVIEW

**Comment by jpvajda** [comment]
should `Validate Pull Request / Run Eslint (pull_request)`  pass on this PR? Not 100% sure if that check applies to the demo

**Comment by jerelmiller** [comment]
@jpvajda Yes! Except for snyk (which never seems to be happy), we should always make sure all validations pass.

**Review by jpvajda — CHANGES_REQUESTED** [review]
we'll want to figure out what the checkout build pr check is failing before merging

**Review by LizBaker — APPROVED** [review]

**Review by jpvajda — APPROVED** [review]

**Comment by jpvajda** [comment]
Once this is merged we can bump the theme on the dev site and then we can cut a dev site release

**Pull request merged**
