### PR TITLE
fix: add `height: 100%` to fix overflow

### PR DESCRIPTION
**Pull request by sunnyzanchi**
## testing

- check out this branch in the theme repo
- in the docs repo:
  - run `cp -r <theme-repo-dir>/packages/gatsby-theme-newrelic/src/components/Tabs/ node_modules/@newrelic/gatsby-theme-newrelic/src/components/Tabs/`
  - `yarn clean`
  - `BUILD_FOLDERS=synthetics yarn start`
  - go to http://localhost:8000/docs/synthetics/synthetic-monitoring/getting-started/get-started-synthetic-monitoring/

### CODE REVIEW

**Comment by tabathadelane** [comment]
i cannot reproduce this on the site.
Screen Shot 2023-04-19 at 1 34 36 PM

**Comment by sunnyzanchi** [comment]
> i cannot reproduce this on the site.

whoops, sorry, that's my bad. i didn't realize there was a different class on tabpanels that were opened than ones that are closed. the class is actually `css-id30ng`

**Review by clarkmcadoo — APPROVED** [review]

**Comment by clarkmcadoo** [comment]
I think the problem here is, we're expecting the overall tabs component to be the height of the largest page up to 500px.  The content causing the issue here is going to 500px and can still scroll, but the Tabs aren't compensating for it.  Maybe we just pass the height all the way back to the Tabs component and set the overall height there?

**Comment by tabathadelane** [comment]
i've followed the steps twice and im still getting this 
Screen Shot 2023-04-20 at 12 00 54 PM

**Review by tabathadelane — APPROVED** [review]
it seems to be working as expected when i copy the files over into the node modules
Screen Shot 2023-04-20 at 12 15 45 PM

**Pull request merged**
