### PR TITLE
new search designs

### PR DESCRIPTION
**Pull request by sunnyzanchi**
this PR implements the designs for the new search experience. it has some dummy data until the functionality is implemented

## testing

- run demo site
- try search in light and dark mode
- resize to smaller screen sizes, the search should shrink as you go
- at all screen sizes, the search should look like the designs

### CODE REVIEW

**Review by LizBaker — APPROVED** [review]
🤩

**Comment by clarkmcadoo** [comment]
The "view more" button isn't hooked up to anything, are we waiting to do that on the docs site? Was just looking at the ticket AC

**Comment by clarkmcadoo** [comment]
Screenshot 2024-10-07 at 11 37 55 AM

We probably want to lose the keyboard buttons on mobile

**Review by clarkmcadoo — CHANGES_REQUESTED** [review]
Let's make the keyboard shortcuts hide on mobile

**Comment by sunnyzanchi** [comment]
> Let's make the keyboard shortcuts hide on mobile

ah good catch, these are definitely supposed to be hidden on mobile

> The "view more" button isn't hooked up to anything, are we waiting to do that on the docs site?

i've got that in the next PR 😄

**Pull request merged**
